name: Release

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always

jobs:
  # --------------------------------------------------------------------------
  # Linux

  armv7-unknown-linux-gnueabihf:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/package-arm
        with:
          arch: armhf
          target: armv7-unknown-linux-gnueabihf
          github_token: ${{ secrets.GITHUB_TOKEN }}
